server.port=8081

# CONFIGURACIÓN DE CONEXIÓN (ORACLE AUTONOMOUS DATABASE)
spring.datasource.url=jdbc:oracle:thin:@cloudbd_high?TNS_ADMIN=C:/Users/56966/Downloads/Wallet_cloudBD
spring.datasource.username=ADMIN
spring.datasource.password=Bases2025$$#
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# CONFIGURACIÓN NATIVA DE WALLET PARA EL POOL DE CONEXIONES
spring.datasource.oracleucp.wallet-location=C:/Users/56966/Downloads/Wallet_cloudBD

# J PA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ACTUATOR & CONSOLAS
spring.h2.console.enabled=false
management.endpoints.web.exposure.include=*

# LOGGING
logging.level.org.springframework.security=DEBUG

# SEGURIDAD JWT
jwt.secret=MI_CLAVE_SUPER_SEGURA_DE_32_O_MAS_BYTES_MINIMO_123456789
jwt.expiration=3600000